title: Fahira Nurul Ichzza # your name (or website title) here
logo: "/images/WhatsApp Image 2021-10-07 at 23.51.491.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Scientist | TensorFlow Developer Certified 
  <br><br>
  Develope machine learning's models
  <br><br>
  <a href="https://www.linkedin.com/in/fahiranurulichzza/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
